In [1]:
import pandas as pd

In [2]:
hb = pd.read_csv("processed/manual_selection_Hiba_20241129.csv", encoding='utf-8')
llt = pd.read_csv("processed/manual_selection_Lalita_20241129.csv", encoding='latin1')
vj = pd.read_csv("processed/manual_selection_Vijay_20241129.csv", encoding='utf-8')

In [3]:
hb = hb.drop(["CNTRY"],axis=1)

In [4]:
hb

,CITY_NAME,FIPS_CNTRY,POP_updated,POP_updated_year,POP_SOURCE_updated,city_type,comments
0,NaN,AC,NaN,NaN,NaN,NaN,"All Saints, 3900, CP, almost 10km to the ocean"
1,NaN,BA,NaN,NaN,NaN,NaN,"Ar-Rifā, 79550, CP, almost 5km"
2,NaN,BB,NaN,NaN,NaN,NaN,"Saint George, 19767, CP, almost 10km to the ocean"
3,NaN,BF,NaN,NaN,NaN,NaN,NaN
4,NaN,BP,NaN,NaN,NaN,NaN,"Tigoa, 881, CP, less than 1000 and also 5km"
...,...,...,...,...,...,...,...
68,NaN,UV,NaN,NaN,NaN,NaN,NaN
69,NaN,UZ,NaN,NaN,NaN,NaN,NaN
70,NaN,WZ,NaN,NaN,NaN,NaN,NaN
71,Siavonga,ZA,"26,951",2022.0,CP,inland,NaN
72,Kariba,ZI,"27,450",2022.0,CP,inland,NaN

In [5]:
llt = llt.drop(["CNTRY_NAME"],axis=1)

In [6]:
llt

,CITY_NAME,FIPS_CNTRY,POP_updated,POP_updated_year,POP_SOURCE_updated,city_type,comments
0,Al Ain,AE,428620.0,2023.0,Abu Dhabi Census - 2023,Inland,NaN
1,Burgges,BE,119869.0,2024.0,https://www.citypopulation.de/en/belgium/cities/,Inland,https://bestat.statbel.fgov.be/bestat/crosstab...
2,Neum,BK,4653.0,2013.0,https://www.citypopulation.de/en/bosnia/herceg...,Coastal,NaN
3,Varna,BU,314607.0,2023.0,https://www.citypopulation.de/en/bulgaria/cities/,Coastal,Pop number @ city level
4,NaN,BX,NaN,NaN,NaN,NaN,Most settlement are along thr coast line/ http...
...,...,...,...,...,...,...,...
61,Kongoussi,UV,53627.0,2019.0,https://www.citypopulation.de/en/burkinafaso/c...,Inland,NaN
62,Kattakurgan,UZ,93423.0,2023.0,https://www.citypopulation.de/en/uzbekistan/ci...,Inland,"There are bigger lakes, but no cities around."
63,NaN,WZ,NaN,NaN,NaN,NaN,NaN
64,Sinazongwe,ZA,15191.0,2022.0,https://www.citypopulation.de/en/zambia/cities/,Inland,Additional:https://zambia.opendataforafrica.or...
65,Kariba,ZI,27450.0,2022.0,https://www.citypopulation.de/en/zimbabwe/cities/,Inland,Additional: https://zimbabwe.opendataforafrica...

In [7]:
vj

,CITY_NAME,FIPS_CNTRY,POP_updated,POP_updated_year,POP_SOURCE_updated,city_type,comments
0,AI Ain,AE,496205.0,2015.0,CityPopulation.de,inland,UAE
1,Bruges,BE,58672.0,2024.0,be.STAT,coastal,Belgium
2,Neum,BK,4358.0,2022.0,CityPopulation.de,coastal,Bosnia and Herzegovina
3,Varna,BU,365995.0,2023.0,Population by towns and sex | National statist...,coastal,Bulgaria
4,NaN,BX,NaN,NaN,NaN,NaN,All cities in Brunei are coastal
5,Sihanoukville,CB,73036.0,2019.0,Final General Population Census 2019-English.pdf,coastal,NaN
6,Moanda,CG,74397.0,2004.0,CityPopulation.de,coastal,Muanda or Moanda is the only coastal city- but...
7,Tartu,EN,95190.0,2021.0,CityPopulation.de,inland,Estonia
8,Assab,ER,44220.0,1997.0,CityPopulation.de,coastal,Eritrea
9,Batumi,GG,169095.0,2020.0,CityPopulation.de,coastal,Georgia
10,Linden,GY,28674.0,2012.0,CityPopulation.de,inland,Guyana
11,Al Faw,IZ,35836.0,2018.0,CityPopulation.de,coastal,Masra in Iraq is not coastal by our definition...
12,Al-'Aqabah,JO,148398.0,2015.0,CityPopulation.de,coastal,Jordan
13,Daugavpils,LG,81074.0,2021.0,CityPopulation.de,inland,Latvia
14,Klaipeda,LH,159403.0,2024.0,CityPopulation.de,coastal,Lithuania
15,Budva,MJ,20168.0,2023.0,CityPopulation.de,coastal,Montenegro
16,NaN,MN,NaN,NaN,NaN,NaN,Monaco is a city state.
17,Izki,MU,23159.0,2020.0,CityPopulation.de,inland,Oman
18,Ash-Shaḥāniyah,QA,67181.0,2020.0,CityPopulation.de,inland,Qatar
19,Constanta,RO,263688.0,2021.0,CityPopulation.de,coastal,Romania
20,Koper,SI,25913.0,2022.0,CityPopulation.de,coastal,Slovenia
21,Maliana,TT,13078.0,2022.0,CityPopulation.de,inland,East Timor
22,Odesa,UP,1010537.0,2022.0,CityPopulation.de,coastal,Ukraine
23,NaN,AC,NaN,NaN,NaN,NaN,Antigua and Barbuda
24,NaN,BA,NaN,NaN,NaN,NaN,Riffa is a coastal city according to our defin...
25,NaN,BB,NaN,NaN,NaN,NaN,Area of Barbados is 432 sq. km. And has no inl...
26,NaN,BF,NaN,NaN,NaN,NaN,The Bahamas is a collection of small islands a...
27,NaN,BP,NaN,NaN,NaN,NaN,The solomon islands also has only coastal citi...
28,NaN,CN,NaN,NaN,NaN,NaN,"In Comoros, all cities are coastal and inland ..."
29,Assomada,CV,21297.0,2021.0,CityPopulation.de,inland,Cape Verde
30,NaN,DO,NaN,NaN,NaN,NaN,"In Dominico, all cities are along the coast (7..."
31,NaN,FJ,NaN,NaN,NaN,NaN,All cities in Fiji are along the coast. (the b...
32,NaN,FM,NaN,NaN,NaN,NaN,All cities in Micronesia are along the coast. ...
33,NaN,GJ,NaN,NaN,NaN,NaN,All cities are along the coast.
34,Selfoss,IC,9812.0,2024.0,Municipalities and urban nuclei - Statistics I...,inland,Iceland
35,NaN,KR,NaN,NaN,NaN,NaN,All cities in Kiribati are coastal.
36,Vacaos/Phoenix,MP,107433.0,2022.0,CityPopulation.de,inland,Mauritius
37,NaN,MT,NaN,NaN,NaN,NaN,All cities in Malta are coastal according to o...
38,NaN,NH,NaN,NaN,NaN,NaN,All cities in Vanutau are coastal.
39,NaN,NR,NaN,NaN,NaN,NaN,Nauru is too small an island to have a second ...
40,NaN,PS,NaN,NaN,NaN,NaN,Palau has only coastal cities.
41,NaN,RM,NaN,NaN,NaN,NaN,Marshall Islands have only costal cities.
42,Antipolo,RP,879301.0,2020.0,CityPopulation.de,inland,Philippines
43,NaN,SC,NaN,NaN,NaN,NaN,All cities are costal in St. Kitts and Nevis.
44,NaN,SE,NaN,NaN,NaN,NaN,All cities in Seychelles are coastal.
45,NaN,SN,NaN,NaN,NaN,NaN,Singapore is a city state.
46,L'Abbayée,ST,1355.0,2022.0,CityPopulation.de,inland,St. Lucia
47,Arima,TD,33606.0,2011.0,CityPopulation.de,inland,Trinidad & Tobago
48,NaN,TN,NaN,NaN,NaN,NaN,Tonga is too small to have inland cities.
49,Trinidade,TP,6685.0,2012.0,CityPopulation.de,inland,Sao Tome & Principe
50,NaN,TV,NaN,NaN,NaN,NaN,Tuvalu
51,NaN,VC,NaN,NaN,NaN,NaN,St. Vincent & the Grenadines
52,NaN,WS,NaN,NaN,NaN,NaN,Samoa

In [8]:
hb['coder'] = 'hb'
llt['coder'] = 'llt'
vj['coder'] = 'vj'

In [9]:
vj.loc[vj['FIPS_CNTRY'] == "AE", 'CITY_NAME'] = "Al Ain"
hb.loc[hb['FIPS_CNTRY'] == "AJ", 'CITY_NAME'] = "Ganja"
hb.loc[hb['FIPS_CNTRY'] == 'KG', 'CITY_NAME'] = 'Balykchy'
vj.loc[vj['FIPS_CNTRY'] == "MP", 'CITY_NAME'] = "Vacoas/Phoenix"
vj.loc[vj['FIPS_CNTRY'] == "QA", 'CITY_NAME'] = "Al Shahaniya"
llt.loc[llt['FIPS_CNTRY'] == "QA", 'CITY_NAME'] = "Al Shahaniya"
vj.loc[vj['FIPS_CNTRY'] == "TP", 'CITY_NAME'] = "Trindade"

In [10]:
df = pd.concat([hb, llt, vj], ignore_index=True)

In [11]:
# Reorder df by 'FIPS_CNTRY'
df = df.sort_values(by='FIPS_CNTRY').reset_index(drop=True)

In [12]:
df

,CITY_NAME,FIPS_CNTRY,POP_updated,POP_updated_year,POP_SOURCE_updated,city_type,comments,coder
0,NaN,AC,NaN,NaN,NaN,NaN,"All Saints, 3900, CP, almost 10km to the ocean",hb
1,NaN,AC,NaN,NaN,NaN,NaN,Antigua and Barbuda,vj
2,Al Ain,AE,496205.0,2015.0,CityPopulation.de,inland,UAE,vj
3,Al Ain,AE,428620.0,2023.0,Abu Dhabi Census - 2023,Inland,NaN,llt
4,NaN,AF,NaN,NaN,NaN,NaN,Biggest lake: Hamun-e Helmand (dry) Ab-i-Estad...,hb
...,...,...,...,...,...,...,...,...
187,NaN,WZ,NaN,NaN,NaN,NaN,NaN,hb
188,Siavonga,ZA,"26,951",2022.0,CP,inland,NaN,hb
189,Sinazongwe,ZA,15191.0,2022.0,https://www.citypopulation.de/en/zambia/cities/,Inland,Additional:https://zambia.opendataforafrica.or...,llt
190,Kariba,ZI,27450.0,2022.0,https://www.citypopulation.de/en/zimbabwe/cities/,Inland,Additional: https://zimbabwe.opendataforafrica...,llt
191,Kariba,ZI,"27,450",2022.0,CP,inland,NaN,hb

In [13]:
# Group by 'FIPS_CNTRY' and 'CITY_NAME', including NaNs
group_counts = df.groupby(['FIPS_CNTRY', 'CITY_NAME'], dropna=False).size().reset_index(name='count')

# Merge the counts back into df
df = df.merge(group_counts, on=['FIPS_CNTRY', 'CITY_NAME'], how='left')

# Create the 'match' column based on the counts
df['match'] = df['count'].apply(lambda x: 1 if x > 1 else 0)

# Drop the 'count' column if it's no longer needed
df.drop(columns=['count'], inplace=True)

In [14]:
df.head(50)

,CITY_NAME,FIPS_CNTRY,POP_updated,POP_updated_year,POP_SOURCE_updated,city_type,comments,coder,match
0,NaN,AC,NaN,NaN,NaN,NaN,"All Saints, 3900, CP, almost 10km to the ocean",hb,1
1,NaN,AC,NaN,NaN,NaN,NaN,Antigua and Barbuda,vj,1
2,Al Ain,AE,496205.0,2015.0,CityPopulation.de,inland,UAE,vj,1
3,Al Ain,AE,428620.0,2023.0,Abu Dhabi Census - 2023,Inland,NaN,llt,1
4,NaN,AF,NaN,NaN,NaN,NaN,Biggest lake: Hamun-e Helmand (dry) Ab-i-Estad...,hb,1
5,NaN,AF,NaN,NaN,NaN,NaN,NaN,llt,1
6,Ganja,AJ,299100,2019.0,CP,inland,NaN,hb,1
7,Ganja,AJ,299100.0,2019.0,https://www.citypopulation.de/en/azerbaijan/ci...,Inland,NaN,llt,1
8,Sevan,AM,18705,2020.0,CP,At Lake,Biggest body of water,hb,1
9,Sevan,AM,18705.0,2022.0,https://www.citypopulation.de/en/armenia/cities/,Inland,NaN,llt,1
10,NaN,AN,NaN,NaN,NaN,Inland,https://www.estadistica.ad/portal/apps/sites/#...,llt,1
11,NaN,AN,NaN,NaN,NaN,NaN,Estany de Juclà - no direct city. Llac d'Engol...,hb,1
12,Bregenz,AU,29643,2024.0,CP,Lake,NaN,hb,1
13,Bregenz,AU,29643.0,2024.0,https://www.citypopulation.de/en/austria/cities/,In Land,NaN,llt,1
14,NaN,BA,NaN,NaN,NaN,NaN,Riffa is a coastal city according to our defin...,vj,1
15,NaN,BA,NaN,NaN,NaN,NaN,"Ar-Rifā, 79550, CP, almost 5km",hb,1
16,NaN,BB,NaN,NaN,NaN,NaN,Area of Barbados is 432 sq. km. And has no inl...,vj,1
17,NaN,BB,NaN,NaN,NaN,NaN,"Saint George, 19767, CP, almost 10km to the ocean",hb,1
18,NaN,BC,NaN,NaN,NaN,NaN,NaN,hb,0
19,Francistown,BC,103417.0,2022.0,https://www.citypopulation.de/en/botswana/,Inland,"If we take Garabone Dam. If not, 2nd city coul...",llt,0
20,Burgges,BE,119869.0,2024.0,https://www.citypopulation.de/en/belgium/cities/,Inland,https://bestat.statbel.fgov.be/bestat/crosstab...,llt,0
21,Bruges,BE,58672.0,2024.0,be.STAT,coastal,Belgium,vj,0
22,NaN,BF,NaN,NaN,NaN,NaN,NaN,hb,1
23,NaN,BF,NaN,NaN,NaN,NaN,The Bahamas is a collection of small islands a...,vj,1
24,Neum,BK,4653.0,2013.0,https://www.citypopulation.de/en/bosnia/herceg...,Coastal,NaN,llt,1
25,Neum,BK,4358.0,2022.0,CityPopulation.de,coastal,Bosnia and Herzegovina,vj,1
26,Copacabana,BL,17431.0,2024.0,https://www.citypopulation.de/en/bolivia/admin...,Inland,Oruro with bigger poppulation 297497 but small...,llt,0
27,Oruro,BL,264943,2012.0,CP,inland,red. 214 km² - biggest lake has no near by cit...,hb,0
28,Vileyka,BO,26811.0,2023.0,https://www.citypopulation.de/en/belarus/cities/,Inland,NaN,llt,0
29,Salihorsk,BO,98590,2023.0,cp,inland,red. around 15 million (roughly) square meters...,hb,0
30,NaN,BP,NaN,NaN,NaN,NaN,The solomon islands also has only coastal citi...,vj,1
31,NaN,BP,NaN,NaN,NaN,NaN,"Tigoa, 881, CP, less than 1000 and also 5km",hb,1
32,NaN,BT,NaN,NaN,NaN,NaN,No cities around the lake with proper populati...,llt,1
33,NaN,BT,NaN,NaN,NaN,NaN,NaN,hb,1
34,Varna,BU,365995.0,2023.0,Population by towns and sex | National statist...,coastal,Bulgaria,vj,1
35,Varna,BU,314607.0,2023.0,https://www.citypopulation.de/en/bulgaria/cities/,Coastal,Pop number @ city level,llt,1
36,NaN,BX,NaN,NaN,NaN,NaN,Most settlement are along thr coast line/ http...,llt,1
37,NaN,BX,NaN,NaN,NaN,NaN,All cities in Brunei are coastal,vj,1
38,Gitega,BY,41944,2008.0,CP,inland,NaN,hb,1
39,Gitega,BY,41944.0,2008.0,https://www.citypopulation.de/en/burundi/cities/,Inland,NaN,llt,1
40,Sihanoukville,CB,71082.0,2019.0,https://www.citypopulation.de/en/cambodia/cities/,Coastal,NaN,llt,1
41,Sihanoukville,CB,73036.0,2019.0,Final General Population Census 2019-English.pdf,coastal,NaN,vj,1
42,NaN,CD,35963.0,2009.0,https://www.citypopulation.de/en/chad/,Inland,No cities around the lake with proper populati...,llt,0
43,Bol,CD,35963,2009.0,CP,inland,NaN,hb,0
44,Moanda,CG,74397.0,2004.0,CityPopulation.de,coastal,Muanda or Moanda is the only coastal city- but...,vj,1
45,Moanda,CG,74397.0,2004.0,https://www.citypopulation.de/en/drcongo/cities/,Coastal,Cannot find more updated data,llt,1
46,NaN,CN,NaN,NaN,NaN,NaN,no city passed the criteria od population and ...,hb,1
47,NaN,CN,NaN,NaN,NaN,NaN,"In Comoros, all cities are coastal and inland ...",vj,1
48,NaN,CT,NaN,NaN,NaN,NaN,No cities around the lake with proper populati...,llt,1
49,NaN,CT,NaN,NaN,NaN,NaN,NaN,hb,1

In [15]:
#df.to_csv("processed/manual_selection_20241129.csv", index=False)

In [16]:
df[df['match'] == 0]['FIPS_CNTRY'].nunique()

20

In [17]:
df[df['match'] == 0]

,CITY_NAME,FIPS_CNTRY,POP_updated,POP_updated_year,POP_SOURCE_updated,city_type,comments,coder,match
18,NaN,BC,NaN,NaN,NaN,NaN,NaN,hb,0
19,Francistown,BC,103417.0,2022.0,https://www.citypopulation.de/en/botswana/,Inland,"If we take Garabone Dam. If not, 2nd city coul...",llt,0
20,Burgges,BE,119869.0,2024.0,https://www.citypopulation.de/en/belgium/cities/,Inland,https://bestat.statbel.fgov.be/bestat/crosstab...,llt,0
21,Bruges,BE,58672.0,2024.0,be.STAT,coastal,Belgium,vj,0
26,Copacabana,BL,17431.0,2024.0,https://www.citypopulation.de/en/bolivia/admin...,Inland,Oruro with bigger poppulation 297497 but small...,llt,0
27,Oruro,BL,264943,2012.0,CP,inland,red. 214 km² - biggest lake has no near by cit...,hb,0
28,Vileyka,BO,26811.0,2023.0,https://www.citypopulation.de/en/belarus/cities/,Inland,NaN,llt,0
29,Salihorsk,BO,98590,2023.0,cp,inland,red. around 15 million (roughly) square meters...,hb,0
42,NaN,CD,35963.0,2009.0,https://www.citypopulation.de/en/chad/,Inland,No cities around the lake with proper populati...,llt,0
43,Bol,CD,35963,2009.0,CP,inland,NaN,hb,0
78,Aqaba,JO,179027.0,2023.0,PopulationEstimatesbyLocality.pdf,Coastal,NaN,llt,0
79,Al-'Aqabah,JO,148398.0,2015.0,CityPopulation.de,coastal,Jordan,vj,0
84,Almaty,KZ,2161797,2023.0,CP,inland,red.,hb,0
85,Atyray,KZ,316468.0,2023.0,https://www.citypopulation.de/en/kazakhstan/ci...,Inland,NaN,llt,0
100,Costesti,MD,2028.0,2014.0,https://www.citypopulation.de/en/moldova/cities/,Inland,NaN,llt,0
101,NaN,MD,NaN,NaN,NaN,NaN,largest lake is 6.26 km²,hb,0
102,Khatgal,MG,3723.0,2021.0,https://www.citypopulation.de/en/mongolia/cities/,Inland,NaN,llt,0
103,Chatgal,MG,3723,2021.0,CP,inland,NaN,hb,0
110,NaN,ML,NaN,NaN,NaN,NaN,NaN,hb,0
111,Raz El Ma,ML,4398.0,2009.0,https://www.citypopulation.de/en/mali/admin/go...,Inland,"Another option would be Essakane, w smaller la...",llt,0
120,NaN,NG,NaN,NaN,NaN,NaN,NaN,hb,0
121,N'Guigmi,NG,23670.0,2012.0,https://www.citypopulation.de/en/niger/cities/,Inland,Arikoukouri (1347ppl) would be closer to the l...,llt,0
124,Pokhara,NP,513504.0,2021.0,https://www.citypopulation.de/en/nepal/cities/,Inland,NaN,llt,0
125,NaN,NP,NaN,NaN,NaN,NaN,NaN,hb,0
130,NaN,PA,NaN,NaN,NaN,NaN,28 square kilometers - Lake Ypoá,hb,0
131,Aregua,PA,70298.0,2022.0,https://www.citypopulation.de/en/paraguay/cities/,Inland,NaN,llt,0
136,NaN,RB,NaN,NaN,NaN,NaN,5.6 km² - palićko,hb,0
137,Zrenjanin,RB,67129.0,2022.0,https://www.citypopulation.de/en/serbia/cities/,Inland,Belo Blato is closer but not on CP,llt,0
142,Antipolo,RP,879301.0,2020.0,CityPopulation.de,inland,Philippines,vj,0
143,Angeles,RP,1598955,2020.0,cp,inland,red. I am not sure where to measure - it is 3...,hb,0
158,Geneva,SZ,206635.0,2023.0,https://www.citypopulation.de/en/switzerland/c...,Inland,NaN,llt,0
159,Lausanne,SZ,144160,2023.0,CP,inland,NaN,hb,0
172,Turkmenbashi,TX,86800.0,2004.0,https://www.citypopulation.de/en/turkmenistan/,Inland,NaN,llt,0
173,Türkmenbaşy,TX,63000,1995.0,CP,inland,NaN,hb,0
178,Kongoussi,UV,53627.0,2019.0,https://www.citypopulation.de/en/burkinafaso/c...,Inland,NaN,llt,0
179,NaN,UV,NaN,NaN,NaN,NaN,NaN,hb,0
180,NaN,UZ,NaN,NaN,NaN,NaN,NaN,hb,0
181,Kattakurgan,UZ,93423.0,2023.0,https://www.citypopulation.de/en/uzbekistan/ci...,Inland,"There are bigger lakes, but no cities around.",llt,0
188,Siavonga,ZA,"26,951",2022.0,CP,inland,NaN,hb,0
189,Sinazongwe,ZA,15191.0,2022.0,https://www.citypopulation.de/en/zambia/cities/,Inland,Additional:https://zambia.opendataforafrica.or...,llt,0